CREATE TABLE IF NOT EXISTS Items (
  `IID` CHAR(5) PRIMARY KEY,
  `QTY` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `COST` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Customer (
  `CID` CHAR(5) PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL,
  `CREDITCARD` INT(9) NOT NULL,
  `ADDRESS` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Order (
  `IID` CHAR(5),
  `CID` CHAR(5)
  `TOTAL` INT NOT NULL, --amount $$
  `COUNT` INT NOT NULL, --item amount
  FOREIGN KEY (`Items`) REFERENCES Items(`IID`),
  FOREIGN KEY (`Customer`) REFERENCES Customer(`CID`),
  PRIMARY KEY (`S`,`P`)
);
